"""Subclass of MyPanel1, which is generated by wxFormBuilder."""

import wx
#import eye_development_gui.eye_development_gui
from eye_development_gui.eye_development_gui import MyPanel1

# Implementing MyPanel1
class eye_development_guiMyPanel1( MyPanel1 ):
	def __init__( self, a, b, c, d, e ):
		MyPanel1.__init__( self, a, b, c, d, e )
	
