"""Subclass of MainFrameBase, which is generated by wxFormBuilder."""

from epithelium_backend.Epithelium import Epithelium
from eye_development_gui.eye_development_gui import MainFrameBase


# Implementing MainFrameBase
class MainFrame(MainFrameBase):
    """Wx frame that contains the entire gui.
     Also acts as both the model and the control for the GUI."""

    def __init__(self, parent):
        """Initializes the GUI and all the data of the model."""
        MainFrameBase.__init__(self, parent)

        self.__active_epithelium = Epithelium(0)  # type: Epithelium

        #  track all the panels that need to be notified when the
        # active epithelium is changed
        self.epithelium_listeners = [self.m_epithelium_gen_display_panel,
                                     self.m_sim_overview_display_panel,
                                     self.m_simulation_display_panel]  # type: list

    @ property
    def active_epithelium(self) -> Epithelium:
        """returns the active epithelium"""
        return self.__active_epithelium

    @ active_epithelium.setter
    def active_epithelium(self, value: Epithelium) -> None:
        """
        Sets the active epithelium and sets the epithelium for
        all listeners.
        :param value: The new active epithelium
        :return: None
        """
        self.__active_epithelium = value

        # notify listeners of change
        for listener in self.epithelium_listeners:
            listener.epithelium = self.__active_epithelium

    def ep_gen_input_validation(self):
        """validates all epithelium generation inputs"""
        # TODO: validate each epithelium generation input
        return True

    def ep_gen_create_callback(self, event):
        """
        Callback for ep_gen_create_button. Attempts to create a
        new epithelium from the epithelium generation inputs
        and sets it as the active epithelium. If creation fails the
        user is notified via popup.
        """
        # TODO: (ep_gen_create_callback) Do what the doc string says this will do

        # validate inputs
        if self.ep_gen_input_validation():

            # convert inputs to usable value

            # min cell count
            min_cell_count_str = ''  # type: str
            for i in range(self.min_cell_count_text_ctrl.GetNumberOfLines()):
                min_cell_count_str += self.min_cell_count_text_ctrl.GetLineText(i)
            min_cell_count = int(min_cell_count_str)  # type: int

            # create epithelium from inputs
            self.active_epithelium = Epithelium(min_cell_count)

        # consume the event
        event.Skip()
