"""Subclass of SimulationPanel, which is generated by wxFormBuilder."""

from eye_development_gui.SimulationPanelBase import SimulationPanel
from epithelium_backend.Epithelium import Epithelium
# Implementing SimulationPanel


class SimulationPanelWrapper(SimulationPanel):

    def __init__(self, parent, a, b, c, d):
        SimulationPanel.__init__(self, parent)

    @property
    def epithelium(self) -> Epithelium:
        """returns the epithelium that is being displayed"""
        return self.m_epithelium_display.epithelium

    @epithelium.setter
    def epithelium(self, value: Epithelium):
        """Sets the epithelium that is to be displayed
        :param value: New epithelium to be displayed
        """
        self.m_epithelium_display.epithelium = value
